// for(var i = 0; i <10; i++)
// {
//     console.log(i);
// }

// // 2 ka table
// for(var i = 2; i <=20; i+2)
// {
//     console.log(i);
// }

// Print numbers Vertcally
// let a = [24, 58, 33, 86, 96, 12, 53, 23, 32, 100]
// for(let i = 0; i <=10; i++)
// {
//     console.log(a[i]);
// }

// // Print using While loop
// let i = 0;
// while(i < 10);
// {
//     console.log(a[1]);
//     i++;
// }

// 2 ka table using do-while loop
let i = 1;
do{
    console.log(i*2);
    i++;
}
while(i <= 10)

// 2 ka table using while loop
let a = 1;
while(i <= 10)
{
    console.log(i*2);
    a++;
}


